package vista;

import javax.swing.*;

public class MdiGeneral extends javax.swing.JFrame {

    /**
     * Creates new form MdiGeneral
     */
    public MdiGeneral() {
        ImageIcon image = new ImageIcon("src/icons/10612410.png");

        setTitle("Recursos humanos Empresa S.A.");
        setIconImage(image.getImage());//Ponemos una imagen como icono de la ventana
        setLocationRelativeTo(null);

        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(MdiGeneral.MAXIMIZED_BOTH);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        // ***** Creacion de barra de menus con sus items *****
        jDesktopPane1 = new JDesktopPane();
        jMenuBar1 = new JMenuBar();
        mnuSesion = new JMenu();
        mnuSesionCambiarSesion = new JMenuItem();
        mnuSesionCerrarSesion = new JMenuItem();
        mnuCatalogos = new JMenu();
        mnuCatalogosMantenimiento = new JMenu();
        mnuCatalogosMantenimientosPuestos = new JMenuItem();
        mnuCatalogosMantenimientosEmpleados = new JMenuItem();
        mnuCatalogosMantenimientosTiposDePagos = new JMenuItem();
        mnuProcesos = new JMenu();
        ProcesoTesoreria = new JMenuItem();
        mnuReportes = new JMenu();
        mnuSeguridad = new JMenu();
        mnuSeguridadBitacora = new JMenuItem();
        mnuAyudas = new JMenu();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        mnuSesion.setText("Sesión");

        mnuSesionCambiarSesion.setText("Cambiar Usuario");
        mnuSesionCambiarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArchivoAbrirSesionActionPerformed(evt);
            }
        });
        mnuSesion.add(mnuSesionCambiarSesion);

        mnuSesionCerrarSesion.setText("Cerrar Sesion");
        mnuSesionCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSesionCerrarSesionActionPerformed(evt);
            }
        });
        mnuSesion.add(mnuSesionCerrarSesion);

        jMenuBar1.add(mnuSesion);

        mnuCatalogos.setText("Catalogos");

        mnuCatalogosMantenimiento.setText("Mantenimientos");

        mnuCatalogosMantenimientosPuestos.setText("Mantenimiento Puestos Laborales");
        mnuCatalogosMantenimientosPuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCatalogosMantenimientosPuestosActionPerformed(evt);
            }
        });
        mnuCatalogosMantenimiento.add(mnuCatalogosMantenimientosPuestos);


        mnuCatalogosMantenimientosEmpleados.setText("Mantenimiento Empleados");
        mnuCatalogosMantenimientosEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCatalogosMantenimientosMaestrosActionPerformed(evt);
            }
        });
        mnuCatalogosMantenimiento.add(mnuCatalogosMantenimientosEmpleados);

        mnuCatalogosMantenimientosTiposDePagos.setText("Mantenimiento TiposDePagos");
        mnuCatalogosMantenimientosTiposDePagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCatalogosMantenimientosTiposDePagosActionPerformed(evt);
            }
        });
        mnuCatalogosMantenimiento.add(mnuCatalogosMantenimientosTiposDePagos);

        mnuCatalogos.add(mnuCatalogosMantenimiento);

        jMenuBar1.add(mnuCatalogos);

        mnuProcesos.setText("Procesos");
        mnuProcesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProcesosActionPerformed(evt);
            }
        });

        ProcesoTesoreria.setText("ProcesoTesoreria");
        ProcesoTesoreria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcesoTesoreriaActionPerformed(evt);
            }
        });
        mnuProcesos.add(ProcesoTesoreria);

        jMenuBar1.add(mnuProcesos);

        mnuReportes.setText("Reportes");
        jMenuBar1.add(mnuReportes);

        mnuSeguridad.setText("Seguridad");

        mnuSeguridadBitacora.setText("Consulta Bitacora");
        mnuSeguridadBitacora.setName("mnuSeguridadBitacora"); // NOI18N
        mnuSeguridadBitacora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSeguridadBitacoraActionPerformed(evt);
            }
        });
        mnuSeguridad.add(mnuSeguridadBitacora);

        jMenuBar1.add(mnuSeguridad);

        mnuAyudas.setText("Ayuda");
        jMenuBar1.add(mnuAyudas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // ****** Funcionalidad de botones y barras de menu ******
    private void mnuCatalogosMantenimientosPuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCatalogosMantenimientosCursosActionPerformed
        // TODO add your handling code here:
        /*MantenimientoCursos ventana = new MantenimientoCursos();
        jDesktopPane1.add(ventana);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        */
    }//GEN-LAST:event_mnuCatalogosMantenimientosCursosActionPerformed

    private void mnuArchivoAbrirSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArchivoAbrirSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuArchivoAbrirSesionActionPerformed

    private void mnuSesionCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArchivoAbrirSesionActionPerformed
        Login login = new Login();
        dispose();
    }//GEN-LAST:event_mnuArchivoAbrirSesionActionPerformed

    private void mnuCatalogosMantenimientosMaestrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCatalogosMantenimientosMaestrosActionPerformed
        // TODO add your handling code here:
        /*MantenimientoMaestros ventana1 = new MantenimientoMaestros();
        jDesktopPane1.add(ventana1);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = ventana1.getSize();
        ventana1.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        */
    }//GEN-LAST:event_mnuCatalogosMantenimientosMaestrosActionPerformed


    private void mnuSeguridadBitacoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSeguridadBitacoraActionPerformed
        // TODO add your handling code here:
        /*frmMantenimientoBitacora ventana = new frmMantenimientoBitacora();
        jDesktopPane1.add(ventana);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        */
    }//GEN-LAST:event_mnuSeguridadBitacoraActionPerformed

    private void mnuCatalogosMantenimientosTiposDePagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCatalogosMantenimientosTiposDePagosActionPerformed
        /*MantenimientoPagos ventana = new MantenimientoPagos();
        jDesktopPane1.add(ventana);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        */
    }//GEN-LAST:event_mnuCatalogosMantenimientosTiposDePagosActionPerformed

    private void mnuProcesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProcesosActionPerformed
        // TODO add your handling code here:
        /*ProcesoTesoreria ventana = new ProcesoTesoreria();
        jDesktopPane1.add(ventana);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        ventana.setVisible(true);
        */
    }//GEN-LAST:event_mnuProcesosActionPerformed

    private void ProcesoTesoreriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcesoTesoreriaActionPerformed
        // TODO add your handling code here:
        /*ProcesoTesoreria ventana = new ProcesoTesoreria();
        jDesktopPane1.add(ventana);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        ventana.setVisible(true);
        */
    }//GEN-LAST:event_ProcesoTesoreriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MdiGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MdiGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MdiGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MdiGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MdiGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ProcesoTesoreria;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuSesion;
    private javax.swing.JMenuItem mnuSesionCambiarSesion;
    private javax.swing.JMenuItem mnuSesionCerrarSesion;
    private javax.swing.JMenu mnuAyudas;
    private javax.swing.JMenu mnuCatalogos;
    private javax.swing.JMenu mnuCatalogosMantenimiento;
    private javax.swing.JMenuItem mnuCatalogosMantenimientosPuestos;
    private javax.swing.JMenuItem mnuCatalogosMantenimientosEmpleados;
    private javax.swing.JMenuItem mnuCatalogosMantenimientosTiposDePagos;
    private javax.swing.JMenu mnuProcesos;
    private javax.swing.JMenu mnuReportes;
    private javax.swing.JMenu mnuSeguridad;
    private javax.swing.JMenuItem mnuSeguridadBitacora;
    // End of variables declaration//GEN-END:variables
}
